services:
    - type: web
      name: metro-reads-server
      plan: free
      runtime: docker
      region: singapore
      healthCheckPath: /admin/login/
      envVars:
          - key: DATABASE_URL
            value: postgresql://metro_reads_db_r4oq_user:lLLun8uQqWKRu2PA8BfC4N9VEMoooWkd@dpg-d2af3ongi27c73f8gst0-a.singapore-postgres.render.com/metro_reads_db_r4oq
          - key: REDIS_URL
            value: rediss://red-d2af3ujipnbc739aobag:sxBOtvHa2ejmhrOhGvlnqlQlPVyA5mdK@singapore-keyvalue.render.com:6379
          - key: SECRET_KEY
            generateValue: true
          - key: PYTHONUNBUFFERED
            value: 1

    - type: worker
      name: metro-reads-celery-worker
      plan: free
      runtime: docker
      region: singapore
      envVars:
          - key: DATABASE_URL
            value: postgresql://metro_reads_db_r4oq_user:lLLun8uQqWKRu2PA8BfC4N9VEMoooWkd@dpg-d2af3ongi27c73f8gst0-a.singapore-postgres.render.com/metro_reads_db_r4oq
          - key: REDIS_URL
            value: rediss://red-d2af3ujipnbc739aobag:sxBOtvHa2ejmhrOhGvlnqlQlPVyA5mdK@singapore-keyvalue.render.com:6379
          - key: SECRET_KEY
            fromService:
                type: web
                name: metro-reads-server
                envVarKey: SECRET_KEY

    - type: worker
      name: metro-reads-celery-beat
      plan: free
      runtime: docker
      region: singapore
      envVars:
          - key: DATABASE_URL
            value: postgresql://metro_reads_db_r4oq_user:lLLun8uQqWKRu2PA8BfC4N9VEMoooWkd@dpg-d2af3ongi27c73f8gst0-a.singapore-postgres.render.com/metro_reads_db_r4oq
          - key: REDIS_URL
            value: rediss://red-d2af3ujipnbc739aobag:sxBOtvHa2ejmhrOhGvlnqlQlPVyA5mdK@singapore-keyvalue.render.com:6379
          - key: SECRET_KEY
            fromService:
                type: web
                name: metro-reads-server
                envVarKey: SECRET_KEY
