# Generated by Django 5.2.4 on 2025-07-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=0.25, help_text='The amount charged per day for an overdue book.', max_digits=4)),
            ],
            options={
                'verbose_name': 'Library Settings',
            },
        ),
    ]
