# Generated by Django 5.2.4 on 2025-09-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=0.25, help_text='The amount charged per day for an overdue book.', max_digits=4)),
                ('loan_duration_days', models.PositiveIntegerField(default=14, help_text='The number of days a member can borrow a book.')),
                ('max_renewals', models.PositiveIntegerField(default=2, help_text='The maximum number of times a loan can be renewed.')),
                ('reservation_expiry_hours', models.PositiveIntegerField(default=24, help_text='The number of hours a member has to borrow a reserved book before the reservation expires.')),
            ],
            options={
                'verbose_name': 'Library Settings',
            },
        ),
    ]
