# Generated by Django 5.2.5 on 2025-09-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarysettings',
            name='loan_duration_days',
            field=models.PositiveIntegerField(default=14, help_text='The number of days a member can borrow a book.'),
        ),
        migrations.AddField(
            model_name='librarysettings',
            name='max_renewals',
            field=models.PositiveIntegerField(default=2, help_text='The maximum number of times a loan can be renewed.'),
        ),
        migrations.AddField(
            model_name='librarysettings',
            name='reservation_expiry_hours',
            field=models.PositiveIntegerField(default=24, help_text='The number of hours a member has to borrow a reserved book before the reservation expires.'),
        ),
    ]
