# Generated by Django 5.2.5 on 2025-09-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_batch_user_department_user_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('GOOD_STANDING', 'Good Standing'), ('FINES_OWED', 'Fines Owed'), ('SUSPENDED', 'Suspended')], default='GOOD_STANDING', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
