# Generated by Django 5.2.5 on 2025-09-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_account_status_user_address_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/user_avatar.png', null=True, upload_to='profile_pics/'),
        ),
    ]
