# Generated by Django 5.2.4 on 2025-08-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='e.g., CSE, EEE, BBA', max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
