# Generated by Django 5.2.5 on 2025-09-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Science Fiction, Mystery, Fantasy', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
