# Generated by Django 5.2.5 on 2025-09-01 12:18

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    """
    Populates the slug for any existing Genre and Department objects.
    """
    Department = apps.get_model("academic", "Department")
    for department in Department.objects.all():
        department.slug = slugify(department.name)
        department.save()

    Genre = apps.get_model("academic", "Genre")
    for genre in Genre.objects.all():
        genre.slug = slugify(genre.name)
        genre.save()


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="slug",
            field=models.SlugField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="genre",
            name="slug",
            field=models.SlugField(max_length=120, null=True),
        ),
        migrations.RunPython(generate_slugs),
        migrations.AlterField(
            model_name="department",
            name="slug",
            field=models.SlugField(max_length=120, unique=True, blank=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(max_length=120, unique=True, blank=True),
        ),
    ]
