# Generated by Django 5.2.5 on 2025-09-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
