# Generated by Django 5.2.4 on 2025-07-16 19:56

import apps.cards.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(default=apps.cards.models.get_expiry_date)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
