# Generated by Django 5.2.5 on 2025-09-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycard',
            name='pdf_card',
            field=models.FileField(blank=True, null=True, upload_to='library_cards/'),
        ),
    ]
