# Generated by Django 5.2.4 on 2025-07-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookqueue',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookqueue',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESERVED', 'Reserved'), ('FULFILLED', 'Fulfilled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20),
        ),
    ]
