# Generated by Django 5.2.5 on 2025-09-01 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_fine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['LIBRARIAN', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_checkouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='renewals_made',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
