# Generated by Django 5.2.6 on 2025-09-04 04:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover_image'),
        ('wishlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_user_book_wishlist',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'book')},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='notes',
        ),
    ]
